import type { WorkEntry } from './types';

export const DATA_VERSION = '3.0'; // Version to force data refresh

export const MONTHS_ORDER: string[] = [
  'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
];

export const WORK_DATA: Omit<WorkEntry, 'id'>[] = [
    { mes: "Mayo", ano: 2024, persona: "Gabriel", trabajo: "Pintura del murete del elevador" },
    { mes: "Mayo", ano: 2024, persona: "Gabriel", trabajo: "Pintura puertas de la basura" },
    { mes: "Mayo", ano: 2024, persona: "Gabriel", trabajo: "Arreglo de lámparas estacionamiento y colocación del sensores" },
    { mes: "Mayo", ano: 2024, persona: "Gabriel", trabajo: "Resane murete del elevador" },
    { mes: "Mayo", ano: 2024, persona: "Gabriel", trabajo: "Resane de la caseta interna" },
    { mes: "Mayo", ano: 2024, persona: "Gabriel", trabajo: "Arreglo de contacto de la caseta interna" },
    { mes: "Mayo", ano: 2024, persona: "Erick", trabajo: "Colocación de lona para la caseta" },
    { mes: "Mayo", ano: 2024, persona: "Erick", trabajo: "Rotura de candados" },
    { mes: "Junio", ano: 2024, persona: "Erick", trabajo: "Sellado del acrílico de la caseta para combatir las filtraciones" },
    { mes: "Junio", ano: 2024, persona: "Erick", trabajo: "Retiro de cables en azotea y estacionamiento" },
    { mes: "Junio", ano: 2024, persona: "Erick", trabajo: "Retiro y lavada de lona de caseta" },
    { mes: "Junio", ano: 2024, persona: "Gabriel", trabajo: "Pintura módulo de la caseta interna" },
    { mes: "Julio", ano: 2024, persona: "Gabriel", trabajo: "Pintura y limpieza de tubos del techo de la caseta" },
    { mes: "Julio", ano: 2024, persona: "Erick", trabajo: "Segundo Sellado del acrílico de la caseta para combatir las filtraciones" },
    { mes: "Julio", ano: 2024, persona: "Erick", trabajo: "Retiro de cables en azotea y estacionamiento" },
    { mes: "Julio", ano: 2024, persona: "Erick", trabajo: "Limpieza Coladeras y barrido de la azotea" },
    { mes: "Agosto", ano: 2024, persona: "Gabriel", trabajo: "Pintura de columnas" },
    { mes: "Agosto", ano: 2024, persona: "Gabriel", trabajo: "Colocación abrazadera viga de tierra" },
    { mes: "Agosto", ano: 2024, persona: "Erick", trabajo: "Retiro de pasto del poste de la calle" },
    { mes: "Agosto", ano: 2024, persona: "Erick", trabajo: "Tercer Sellado del acrílico de la caseta para combatir las filtraciones" },
    { mes: "Agosto", ano: 2024, persona: "Erick", trabajo: "Podada de jardinera de la entrada" },
    { mes: "Septiembre", ano: 2024, persona: "Gabriel", trabajo: "Pintura de botes de basura" },
    { mes: "Septiembre", ano: 2024, persona: "Gabriel", trabajo: "Cuarto Sellado del acrílico de la caseta para combatir las filtraciones" },
    { mes: "Octubre", ano: 2024, persona: "Gabriel", trabajo: "Cambio botón portón" },
    { mes: "Octubre", ano: 2024, persona: "Gabriel", trabajo: "Lavado filtro de agua" },
    { mes: "Noviembre", ano: 2024, persona: "Gabriel", trabajo: "Cambio de flotador cisterna 3 e instalación llave de paso" },
    { mes: "Noviembre", ano: 2024, persona: "Gabriel", trabajo: "Lavado rejillas sótano" },
    { mes: "Noviembre", ano: 2024, persona: "Erick", trabajo: "Cambio lámpara elevador" },
    { mes: "Diciembre", ano: 2024, persona: "Gabriel", trabajo: "Instalación de hule en rejilla de la rampa" },
    { mes: "Diciembre", ano: 2024, persona: "Erick", trabajo: "Colocación de adornos de Navidad" },
    { mes: "Enero", ano: 2025, persona: "Gabriel", trabajo: "Limpieza del filtro de agua con karcher" },
    { mes: "Enero", ano: 2025, persona: "Gabriel", trabajo: "Colocación de base y lámpara de estacionamiento (solicitado por Renata)" },
    { mes: "Enero", ano: 2025, persona: "Gabriel", trabajo: "Colocación del botón del portón de caseta externa y resane de tablaroca" },
    { mes: "Enero", ano: 2025, persona: "Gabriel", trabajo: "Instalación de hule en rejilla de la rampa por 2a. vez, los anteriores desaparecieron" },
    { mes: "Enero", ano: 2025, persona: "Erick", trabajo: "Retiro de adornos de Navidad" },
    { mes: "Febrero", ano: 2025, persona: "Gabriel", trabajo: "Arreglo de pintura y resane jardinera exterior" },
    { mes: "Marzo", ano: 2025, persona: "Gabriel", trabajo: "Limpieza del filtro de agua con karcher" },
    { mes: "Marzo", ano: 2025, persona: "Erick", trabajo: "Cambio lámpara elevador" },
    { mes: "Abril", ano: 2025, persona: "Gabriel", trabajo: "Limpieza pasto banqueta" },
    { mes: "Abril", ano: 2025, persona: "Gabriel", trabajo: "Ajuste y aceitada puerta de la caseta externa" },
    { mes: "Abril", ano: 2025, persona: "Gabriel", trabajo: "Arreglo de la chapa de la caseta externa" },
    { mes: "Abril", ano: 2025, persona: "Erick", trabajo: "Cambio lámpara elevador" },
    { mes: "Abril", ano: 2025, persona: "Erick", trabajo: "Poda jardinera externa" },
    { mes: "Mayo", ano: 2025, persona: "Gabriel", trabajo: "Colocación de lona en la caseta. Limpieza y sellado del acrílico" },
    { mes: "Mayo", ano: 2025, persona: "Gabriel", trabajo: "Ajuste de cables sueltos de servicios en la azotea (colocación de zinchos)" },
    { mes: "Mayo", ano: 2025, persona: "Gabriel", trabajo: "Limpieza de cables de azotea cortados. Barrida de azotea y limpieza de coladeras" },
    { mes: "Mayo", ano: 2025, persona: "Gabriel", trabajo: "Colado Cubetas de concreto" },
    { mes: "Junio", ano: 2025, persona: "Gabriel", trabajo: "Lavada Filtro" },
    { mes: "Junio", ano: 2025, persona: "Gabriel", trabajo: "Limpieza cuarto azotea" },
    { mes: "Junio", ano: 2025, persona: "Gabriel", trabajo: "Colocación Lona cuarto máquinas elevador" },
    { mes: "Julio", ano: 2025, persona: "Gabriel", trabajo: "Lavada del filtro de agua" },
    { mes: "Julio", ano: 2025, persona: "Gabriel", trabajo: "Colocación Pichancha en la cisterna" },
    { mes: "Julio", ano: 2025, persona: "Gabriel", trabajo: "Lavado de la cisterna" },
    { mes: "Julio", ano: 2025, persona: "Gabriel", trabajo: "Lavado de todos los cubos con lama del edificio en el nivel de estacionamiento (6 cubos)" },
    { mes: "Agosto", ano: 2025, persona: "Gabriel", trabajo: "Arreglo de 2 bases de lámparas del estacionamiento, cambio de 2 lámparas y colocación de 2 sensores de luz" },
    { mes: "Agosto", ano: 2025, persona: "Gabriel", trabajo: "Colocación de 4 sensores de luz en cada piso del edificio" },
    { mes: "Agosto", ano: 2025, persona: "Gabriel", trabajo: "Limpieza del pasto del poste afuera del edificio y plantó varios cactus" },
    { mes: "Agosto", ano: 2025, persona: "Gabriel", trabajo: "Se sembraron varios cactus en la jardinera externa" },
    { mes: "Agosto", ano: 2025, persona: "Gabriel", trabajo: "Cambio del foco del elevador" }
];
